services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamo-db
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - dynamo-db-data:/home/dynamodblocal/data
    env_file:
      - .env
    user: root
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"

volumes:
  dynamo-db-data:
